#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Make multicomponent film module
cd applications/modules/multicomponentFilm
./Allwmake
cd ../../..

# Make supporting source code
cd src
wmake $targetType enhancementModels
wmake $targetType massTransferRateCoefficientModels
wmake $targetType interphaseMassTransferModels
wmake $targetType reactions
wmake $targetType fvModels
wmake $targetType derivedFvPatchFields

#------------------------------------------------------------------------------
