#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean multicomponent film module
cd applications/modules/multicomponentFilm
./Allwclean
cd ../../..

# Clean supporting source code
cd src
wclean libso enhancementModels
wclean libso massTransferRateCoefficientModels
wclean libso interphaseMassTransferModels
wclean libso reactions
wclean libso fvModels
wclean libso derivedFvPatchFields

#------------------------------------------------------------------------------
